keys:
  - &admin_ehpc age1x92egx7heav7rakx73ax4c925wzyfudekh6xwrgpuswygp8c9gvs5jnhac
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_ehpc
